name: 'Comment on new issue'
description: 'Comment on issue with a defined message whenever someone creates a new issue.'
inputs:
  token:
    description: "GitHub token"
    required: true
  message: 
    description: 'Message to as comment body'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'